### ISSUE TITLE
It Doesn't Work

### ISSUE THREAD

**Issue by MainMemory** [sonicretro/SCDSteamModLoader#1]
The mod loader causes the game to crash as soon as it tries to load a file from the RSDK after loading a file from a mod. Currently, the only way to make mods work is to ensure that the mod contains all the game's files.

**Comment by fancythedeveloper** [comment]
Just saying but, does this mod loader uses Sonic Mania's loader as a base? Since they both use the same engine, it's just that Mania's a bit more updated.

**Comment by MainMemory** [comment]
It uses some code that's common to all my mod loaders, but no, I coded this loader specifically for Sonic CD Steam. The way Sonic Mania loads files is different than how this game does it.

**Comment by MainMemory** [comment]
Oops, this was fixed by 56d320d658e69f01dfc8380c70a413448e5c0658.
